name: tests

on:
  pull_request:

jobs:
  tests:
    name: Run Tests and Show Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
        pip install coverage pytest

    - name: Run pytest with coverage
      run: |
        if [ -d tests/ ]; then
          coverage run --source=scgenokit/ -m pytest tests/
          coverage report -m
          coverage json -q
        fi

    - name: Compute diff coverage and print to log
      run: |
        if [ -f coverage.json ]; then
          git fetch -q origin ${{ github.event.pull_request.head.ref }} --depth $(( ${{ github.event.pull_request.commits }} + 1 ))
          git fetch -q origin ${{ github.event.pull_request.base.ref }}
          git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > diff.txt
          
          echo "📊 Calculating diff coverage with threshold = 0%"
          threshold_pct=0
          python .github/workflows/diff_coverage.py --threshold $threshold_pct diff.txt coverage.json > diff_coverage.txt

          echo "📋 Diff coverage result:"
          cat diff_coverage.txt

          echo "📋 Full coverage report:"
          coverage report -m
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
